package persistence

var Public_stripe_key = "pk_test_51MAHiuLcHuAQvef6neN3R1mcKF3jQ7GfzTHgOUvjWhmNDXmlVtwyxUEu5zNwfrATbq5CG7NrIOYjuTBzrga4I8Ej00wdzWy8Ew"
var Private_stripe_key = "sk_test_51MAHiuLcHuAQvef6gXQoWqhUaUehxakK3rKFERYbq6QCPH9KInBRZSIRUo7mJxJhUOSuTHeoC2nZ6fPzlCCCkbg100zzilkAEY"
